openapi: 3.0.1
info:
  title: RSS reader API 
  description: The API used to read RSS feeds
  contact:
    email: maciej.galkowski@gmail.com
  version: "1"
paths:
  /sources:
    get: 
      summary: Get the list of available feeds 
      responses:
        200:
          description: The feedID should be used in the query to select the active RSS feeds
          content:
            application/json:
              schema:
                type: object
                properties:
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        sourceID:
                          type: string
                          description: |
                            String uniquely identifying the feed
                          example: "1"
                        category:
                          type: array
                          items:
                            type: string
                          description: Category of the feed, such as UK or Technology
                        sourceURL:
                          type: string
                          description: Url of the RSS feed
                        summary: 
                          type: string
                          description: A short description of the feed
                        title:
                          type: string
                          description: Feed title
         
  /feeds:
    get:
      summary: |
        Retrieved articles from the RSS feeds. The articles can be filterd based on the 
        source ID and source category.
      parameters:
      - name: maxtimestamp
        in: query
        description: |
          Unix timestamp marking the newest feed that sould be returned. If empty, the current 
          timestamp is used
        required: false
        schema:
          type: integer
      - name: sources
        in: query
        description: |
          A list of sources to retrieve articles from. If not set, defaults to all sources.
        schema:
          type: array
          items:
            type: string
        explode: false
        example: "sources=1,2,4"
      - name: categories
        in: query
        description: |
          A list of categories to be applied as a filter for the returned article list.
          If not set, defaults to all categories
        schema:
          type: array
          items:
            type: string
        explode: false
        example: "categories=technology,UK"
      - name: count
        in: query
        description: Number of feeds to retrieve
        schema:
          type: integer
          default: 10
        example: 10
          
      responses:
        200:
          description: The list of articles 
          content:
            application/json:
              schema:
                type: object